"""Gateway WhatsApp Zeline lewat bridge Baileys (Node.js).

Ini memakai WhatsApp multi-device (QR pairing), bukan WhatsApp Business Cloud API.
Alur aman:

    WhatsApp <-> Baileys bridge (localhost:8771) <-> Python (localhost:8770)

Dua sisi localhost memakai token acak per runtime. Pesan outgoing diabaikan
(``fromMe``) supaya bot tidak membalas dirinya sendiri.
"""
from __future__ import annotations

import hmac
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import requests

from zeline import config
from zeline.agent import ZelineError

BRIDGE_DIR = config.DATA_DIR / "wa-bridge"
DEFAULT_CALLBACK_PORT = 8770
DEFAULT_BRIDGE_PORT = 8771
MAX_BODY_BYTES = 32_000


_FENCED_CODE_RE = re.compile(r"```[A-Za-z0-9_+.-]*\n?.*?```", re.DOTALL)


def _markdown_to_whatsapp(text: str) -> str:
    """Adaptasi subset Markdown umum tanpa mengubah isi fenced code."""
    code_blocks: list[str] = []

    def keep_code(match: re.Match[str]) -> str:
        code_blocks.append(match.group(0))
        return f"\x00CODE{len(code_blocks) - 1}\x00"

    rendered = _FENCED_CODE_RE.sub(keep_code, text)
    rendered = re.sub(r"(?m)^#{1,6}\s+(.+)$", r"*\1*", rendered)
    rendered = re.sub(r"\*\*(.+?)\*\*", r"*\1*", rendered, flags=re.DOTALL)
    for index, block in enumerate(code_blocks):
        rendered = rendered.replace(f"\x00CODE{index}\x00", block)
    return rendered

PACKAGE_JSON = {
    "name": "zeline-wa-bridge",
    "private": True,
    "type": "commonjs",
    "dependencies": {
        "@whiskeysockets/baileys": "7.0.0-rc14",
        "qrcode-terminal": "^0.12.0",
    },
}

# File .cjs sengaja plain Node supaya package Python tidak membawa dependency Node.
BRIDGE_SOURCE = r'''/* Zeline WhatsApp Baileys bridge. Generated by Zeline. */
const http = require('http');
const qrcode = require('qrcode-terminal');
const baileys = require('@whiskeysockets/baileys');

const makeWASocket = baileys.default;
const { useMultiFileAuthState, DisconnectReason, Browsers } = baileys;
const CALLBACK_URL = process.env.ZELINE_WA_CALLBACK_URL || 'http://127.0.0.1:8770';
const BRIDGE_TOKEN = process.env.ZELINE_WA_BRIDGE_TOKEN || '';
const PORT = Number(process.env.ZELINE_WA_BRIDGE_PORT || '8771');
const MAX_BODY = 32000;
let sock = null;

function authorized(req) {
  const supplied = req.headers['x-zeline-bridge'] || '';
  return BRIDGE_TOKEN && supplied === BRIDGE_TOKEN;
}

async function forwardIncoming(from, text) {
  const response = await fetch(CALLBACK_URL + '/incoming', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-zeline-bridge': BRIDGE_TOKEN,
    },
    body: JSON.stringify({ from, text }),
  });
  if (!response.ok) console.log('[bridge] callback HTTP ' + response.status);
}

function extractText(message) {
  return message?.conversation || message?.extendedTextMessage?.text || '';
}

async function startSocket() {
  const { state, saveCreds } = await useMultiFileAuthState(__dirname + '/auth');
  sock = makeWASocket({
    auth: state,
    browser: Browsers.ubuntu('Zeline'),
    printQRInTerminal: false,
    markOnlineOnConnect: false,
    syncFullHistory: false,
  });

  sock.ev.on('creds.update', saveCreds);
  sock.ev.on('connection.update', (update) => {
    if (update.qr) qrcode.generate(update.qr, { small: true });
    if (update.connection === 'open') console.log('[bridge] WhatsApp connected');
    if (update.connection === 'close') {
      const code = update.lastDisconnect?.error?.output?.statusCode;
      const loggedOut = code === DisconnectReason.loggedOut;
      console.log('[bridge] connection closed' + (loggedOut ? ' (logout)' : ', reconnecting'));
      if (loggedOut) process.exit(1);
      setTimeout(startSocket, 1500);
    }
  });

  sock.ev.on('messages.upsert', async ({ messages }) => {
    for (const message of messages || []) {
      // PENTING: tanpa fromMe, bot akan membalas jawaban bot sendiri.
      if (!message?.message || message.key?.fromMe) continue;
      const from = message.key?.remoteJid;
      const text = extractText(message.message).trim();
      if (!from || !text || from === 'status@broadcast') continue;
      try { await forwardIncoming(from, text); }
      catch (err) { console.log('[bridge] callback failed: ' + err.message); }
    }
  });
}

http.createServer((req, res) => {
  if (req.method !== 'POST' || req.url !== '/send') {
    res.statusCode = 404; return res.end('not found');
  }
  if (!authorized(req)) {
    res.statusCode = 401; return res.end('unauthorized');
  }
  let raw = '';
  req.on('data', (chunk) => {
    raw += chunk;
    if (raw.length > MAX_BODY) req.destroy();
  });
  req.on('end', async () => {
    try {
      const body = JSON.parse(raw || '{}');
      const to = String(body.to || '');
      const text = String(body.text || '');
      if (!to || !text) throw new Error('to/text required');
      if (!sock) throw new Error('WhatsApp not connected yet');
      await sock.sendMessage(to, { text });
      res.end('ok');
    } catch (err) {
      res.statusCode = 500; res.end(String(err.message || err));
    }
  });
}).listen(PORT, '127.0.0.1', () => console.log('[bridge] HTTP ready on 127.0.0.1:' + PORT));

startSocket().catch((err) => { console.error('[bridge] fatal:', err); process.exit(1); });
'''


def info() -> dict[str, str]:
    return {
        "label": "WhatsApp",
        "hint": "Requires Node.js; the first serve installs the bridge then shows a QR for Linked Devices.",
    }


def validate_config(cfg: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    profile = str(cfg.get("tool_profile", "safe"))
    if profile not in {"safe", "workspace", "full"}:
        errors.append(f"invalid WhatsApp tool_profile: {profile}")
    if not isinstance(cfg.get("allowed", []), list):
        errors.append("WhatsApp allowed must be a list of numbers/JIDs")
    ports: dict[str, int] = {}
    for field, default in (("callback_port", DEFAULT_CALLBACK_PORT), ("bridge_port", DEFAULT_BRIDGE_PORT)):
        try:
            port = int(cfg.get(field, default))
            if not 1 <= port <= 65535:
                errors.append(f"{field} must be 1–65535")
            else:
                ports[field] = port
        except (TypeError, ValueError):
            errors.append(f"{field} is invalid")
    if len(ports) == 2 and ports["callback_port"] == ports["bridge_port"]:
        errors.append("callback_port and bridge_port must differ")
    return errors


def render_bridge(bridge_token: str) -> str:
    """Exposed for test: source must carry anti-loop + bridge authentication."""
    del bridge_token  # Runtime token masuk environment, tidak di-embed dalam source.
    return BRIDGE_SOURCE


def _normalize_jid(value: Any) -> str:
    raw = str(value).strip().lower()
    # WhatsApp device JID sometimes has device suffix `number:device@s.whatsapp.net`.
    local, separator, domain = raw.partition("@")
    local = local.split(":", 1)[0].replace("+", "").replace(" ", "").replace("-", "")
    return f"{local}@{domain}" if separator else local


def _is_allowed(jid: str, allowed: list[Any]) -> bool:
    if not allowed:
        return True
    normalized = _normalize_jid(jid)
    number = normalized.split("@", 1)[0]
    options = {_normalize_jid(item) for item in allowed}
    return normalized in options or number in options


def _split_message(text: str, limit: int = 4_000) -> list[str]:
    if len(text) <= limit:
        return [text]
    parts: list[str] = []
    remaining = text
    while len(remaining) > limit:
        cut = max(remaining.rfind("\n", 0, limit), remaining.rfind(" ", 0, limit))
        if cut < limit // 2:
            cut = limit
        parts.append(remaining[:cut].rstrip())
        remaining = remaining[cut:].lstrip()
    if remaining:
        parts.append(remaining)
    return parts


def _ensure_bridge() -> Path:
    if shutil.which("node") is None or shutil.which("npm") is None:
        raise RuntimeError("Node.js and npm are required for the WhatsApp gateway. Install Node.js >=18 first.")
    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(BRIDGE_DIR, 0o700)
    except OSError:
        pass
    (BRIDGE_DIR / "package.json").write_text(json.dumps(PACKAGE_JSON, indent=2) + "\n", encoding="utf-8")
    (BRIDGE_DIR / "bridge.cjs").write_text(BRIDGE_SOURCE, encoding="utf-8")
    package_path = BRIDGE_DIR / "node_modules" / "@whiskeysockets" / "baileys"
    if not package_path.exists():
        print("  [whatsapp] install Baileys (sekali saja)…", flush=True)
        result = subprocess.run(
            ["npm", "install", "--omit=dev", "--no-audit", "--no-fund"],
            cwd=str(BRIDGE_DIR),
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError("npm install Baileys gagal")
    return BRIDGE_DIR


def _authorized(headers, bridge_token: str) -> bool:
    return hmac.compare_digest(str(headers.get("X-Zeline-Bridge", "")), bridge_token)


def start(sessions, cfg: dict[str, Any], stop_event) -> None:
    errors = validate_config(cfg)
    if errors:
        raise RuntimeError("; ".join(errors))
    bridge_dir = _ensure_bridge()
    callback_port = int(cfg.get("callback_port", DEFAULT_CALLBACK_PORT))
    bridge_port = int(cfg.get("bridge_port", DEFAULT_BRIDGE_PORT))
    bridge_token = secrets.token_urlsafe(32)
    allowed = cfg.get("allowed", [])
    allow_groups = bool(cfg.get("allow_groups", False))
    tool_profile = str(cfg.get("tool_profile", "safe"))

    def send_to_whatsapp(to: str, text: str) -> None:
        for part in _split_message(_markdown_to_whatsapp(text)):
            try:
                response = requests.post(
                    f"http://127.0.0.1:{bridge_port}/send",
                    headers={"X-Zeline-Bridge": bridge_token},
                    json={"to": to, "text": part},
                    timeout=20,
                )
                if not response.ok:
                    print(f"  [whatsapp] send failed HTTP {response.status_code}", flush=True)
            except requests.RequestException as exc:
                print(f"  [whatsapp] send failed: {exc.__class__.__name__}", flush=True)

    def process_incoming(jid: str, text: str) -> None:
        is_group = jid.endswith("@g.us")
        if is_group and not allow_groups:
            return
        if not _is_allowed(jid, allowed):
            return  # WA tidak perlu mengumumkan allowlist kepada spammer.
        try:
            reply = sessions.send(
                identity=f"whatsapp:{jid}",
                text=text,
                tool_profile=tool_profile,
            )
        except ZelineError as exc:
            reply = f"⚠️ Zeline hit a problem: {exc}"
        except Exception as exc:
            print(f"  [whatsapp] unhandled agent error: {exc.__class__.__name__}: {exc}", flush=True)
            reply = f"⚠️ Zeline hit an unexpected internal error ({exc.__class__.__name__}). Please try again in a moment."
        send_to_whatsapp(jid, reply)

    class CallbackHandler(BaseHTTPRequestHandler):
        def do_POST(self) -> None:
            if self.path.rstrip("/") != "/incoming" or not _authorized(self.headers, bridge_token):
                self.send_response(401)
                self.end_headers()
                return
            try:
                length = int(self.headers.get("Content-Length", "0"))
                if not 0 < length <= MAX_BODY_BYTES:
                    raise ValueError("body size")
                body = json.loads(self.rfile.read(length))
                jid = str(body.get("from", "")).strip()
                text = str(body.get("text", "")).strip()
                if not jid or not text:
                    raise ValueError("message fields")
            except (ValueError, TypeError, json.JSONDecodeError):
                self.send_response(400)
                self.end_headers()
                return
            threading.Thread(target=process_incoming, args=(jid, text), daemon=True).start()
            self.send_response(202)
            self.end_headers()

        def log_message(self, _format: str, *_args: Any) -> None:
            return

    callback = ThreadingHTTPServer(("127.0.0.1", callback_port), CallbackHandler)
    callback.timeout = 0.5
    env = {
        **os.environ,
        "ZELINE_WA_CALLBACK_URL": f"http://127.0.0.1:{callback_port}",
        "ZELINE_WA_BRIDGE_TOKEN": bridge_token,
        "ZELINE_WA_BRIDGE_PORT": str(bridge_port),
    }
    process = subprocess.Popen(
        ["node", "bridge.cjs"],
        cwd=str(bridge_dir),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    def pump_output() -> None:
        if process.stdout is None:
            return
        for line in process.stdout:
            sys.stdout.write("  [wa-bridge] " + line.decode(errors="replace"))
            sys.stdout.flush()

    threading.Thread(target=pump_output, daemon=True).start()
    print("  [whatsapp] bridge start; scan QR yang tampil di terminal", flush=True)
    try:
        while not stop_event.is_set() and process.poll() is None:
            callback.handle_request()
    finally:
        callback.server_close()
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
        print("  [whatsapp] stopped", flush=True)
